name:       'CSE 440'
baseurl:    '/courses/cse440/15au'

brandimage: ''
brandtext:  'CSE 440 - Introduction to HCI - Autumn 2015'

navbar:
  items:
    - text: 'Calendar'
      link: 'calendar.html'

exclude:
  # Python
  - env34
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests

collections:
  assignments:
    output: true
